name: ci

on:
  - push

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 5

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.42.1

  unit:
    name: Unit Tests
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go: [1.15, 1.16, 1.17]
    steps:
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 5

      - name: Test
        run: |
          make test
